# NumPy Review
This notebook provides a hands-on review of essential NumPy operations, including array creation, manipulation, arithmetic, and more.

In [4]:
%pip install numpy


[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


## 1. Creating a NumPy Array
Create a NumPy array from a Python list.

In [1]:
import numpy as np

# 1. Create a numpy array
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

Array: [1 2 3 4 5]


## 2. Arrays of Zeros and Ones
Create arrays filled with zeros and ones.

In [3]:
# 2. Array of zeros and ones
zeros = np.zeros((2, 4))
ones = np.ones((2, 4))
print("Zeros:\n", zeros)
print("Ones:\n", ones)

Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 3. Array with Random Values
Create an array with random values.

In [5]:
# 3. Array with random values
rand_arr = np.random.rand(2, 3)
print("Random Array:\n", rand_arr)

Random Array:
 [[0.30470812 0.47294772 0.63384643]
 [0.92662859 0.22387655 0.7725095 ]]


## 4. Reshaping Arrays
Reshape an existing array to a new shape.

In [7]:
# 4. Reshape an array
print("Array:\n", arr)

reshaped = arr.reshape((5, 1))
print("Reshaped Array:\n", reshaped)

Array:
 [1 2 3 4 5]
Reshaped Array:
 [[1]
 [2]
 [3]
 [4]
 [5]]


## 4. Reshaping Arrays (Duplicate Example)
Another example of reshaping an array.

In [9]:
# 4. Reshape an array
reshaped = arr.reshape((5, 1))
print("Reshaped Array:\n", reshaped)

Reshaped Array:
 [[1]
 [2]
 [3]
 [4]
 [5]]


## 5. Basic Arithmetic Operations
Perform element-wise arithmetic operations on arrays.

In [8]:
# 5. Basic arithmetic operations
print("Array:\n", arr)

arr2 = np.array([10, 20, 30, 40, 50])
sum_arr = arr + arr2
print("Sum:", sum_arr)

Array:
 [1 2 3 4 5]
Sum: [11 22 33 44 55]


## 6. Slicing and Indexing
Access specific elements or slices of an array.

In [ ]:
# 6. Slicing and indexing
print("Array:\n", arr)

print("First three elements:", arr[:3])

Array:
 [1 2 3 4 5]
First three elements: [1 2 3]
Last 2 elements: [3]


## 7. Aggregate Functions
Calculate aggregate statistics such as mean, sum, and max.

In [19]:
# 7. Aggregate functions
print("Array:\n", arr)
print("Mean:", arr.mean())
print("Sum:", arr.sum())
print("Max:", arr.max())
print("Min:", arr.min())

Array:
 [1 2 3 4 5]
Mean: 3.0
Sum: 15
Max: 5
Min: 1


## 8. Matrix Multiplication
Perform matrix multiplication using NumPy arrays.

In [13]:
# 8. Matrix multiplication
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
mat_mul = np.dot(mat1, mat2)
print("Matrix Multiplication:\n", mat_mul)


Matrix Multiplication:
 [[19 22]
 [43 50]]


## 9. Transpose
Transpose a matrix (swap rows and columns).

In [ ]:
# 9. Transpose
print("Transpose:\n", mat1.T)


Transpose:
 [[1 3]
 [2 4]]


## 10. Boolean Indexing
Select elements from an array based on a condition.

In [21]:
# 10. Boolean indexing
print("Elements > 2:", arr[arr > 2])

Elements > 2: [3 4 5]
